---
name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: docker build -t your-ecr-repository-uri:latest .

      - name: Tag Docker image
        run: docker tag your-ecr-repository-uri:latest ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ACCOUNT_ID }}/${{ secrets.AWS_ECR_REPOSITORY }}:latest

      - name: Push Docker image to ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ACCOUNT_ID }}/${{ secrets.AWS_ECR_REPOSITORY }}:latest

      - name: SSH into EC2 and pull updated image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ACCOUNT_ID }}/${{ secrets.AWS_ECR_REPOSITORY }}:latest
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker run -d -p 5000:5000 --name your-container-name ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ACCOUNT_ID }}/${{ secrets.AWS_ECR_REPOSITORY }}:latest
